### ISSUE TITLE
Can we generate instances using ecole?

### ISSUE THREAD

**Issue by thupchnsky** [ds4dm/branch-search-trees#2]
Dear authors,

I know that the instances you used are from some standard library, but I am wondering if there is a way to generate some synthetic instances by ecole (the platform also from your group)? Is it possible? I have used ecole for some time. For the candidate node embedding I guess we can use the node_observation.column_features (maybe plus some post-processing transform to get what you designed in paper), but I could not find a way to find a cutoff value for a MILP problem in ecole. Is the cutoff value necessary here?

Thanks anyway for this interesting work and I like it very much!

**Comment by vis-opt** [comment]
Unfortunately we did not develop the project with any sort of Ecole compatibility. I am not sure how well we could provide support or guidance on how to cross-pollinate our repo with the more general Ecole platform (sorry about this). 

I am not familiar with what exactly the `node_observation.column_features` returns, but I want to point out that our TreeState is a concatenation of the currently selected node features and general features of the B&B search tree itself. You might have to make a judgment call as to how well it approximates the TreeState in the paper. 

In terms of the specific question of providing a cut-off value, no I do not believe it is necessary. We did this because it is used in MILP research settings. Perhaps you can provide a cutoff of 1e+20, some large value that effectively disables cutoff dynamics during the B&B search. You may observe different dynamics without the cutoff. 

Hope this helps.

**Comment by thupchnsky** [comment]
Thanks for your reply! I looked into the class `SCIPCollectEnv` a little bit and I guess the only thing related to the dataset files is 
```python
m = scip.Model()
m.readProblem(instance)
```
I think this should work for any compressed file as long as it has the same structure as the `*.mps.gz` files as provided in the training and testing instances. Is that right? However, when I tried to read a bit more about this readProblem function, the link in the online document about `pyscipopt.scip.Model.readProblem()` is 404. So I am wondering if I want to build a custom instance (lets say I know what are the objectives and constraints), how should I generate the `*.mps.gz` file so it is recognizable to `pyscipopt.scip.Model`? Thanks!

**Comment by vis-opt** [comment]
MPS is a file format with its own schema: https://en.wikipedia.org/wiki/MPS_%28format%29. I do not have experience generating instances in this format, all ours were already in this mps format with already setup data-loaders via SCIP. 

For further help you may have to consult SCIP support.

**Comment by thupchnsky** [comment]
Ok I see. Thanks for your help anyway!
